# Generated by Django 4.2.7 on 2023-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_complete',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
