# Generated by Django 4.2.7 on 2023-11-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_history_date_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='history',
            name='task_completed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.task'),
        ),
    ]
